# Generated by Django 4.2.4 on 2024-02-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='date',
        ),
    ]
