# Generated by Django 4.2.4 on 2024-05-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edai', '0003_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='video',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
