# Generated by Django 4.2.4 on 2024-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edai', '0004_location_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(default=0, upload_to='uploads/'),
        ),
    ]
