# Generated by Django 4.2.4 on 2024-05-28 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edai', '0005_alter_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 15)),
        ),
    ]
