# Generated by Django 4.2.4 on 2024-05-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edai', '0006_location_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date_diff',
            field=models.IntegerField(default=0),
        ),
    ]
